### ISSUE TITLE
Broken for html. :(

### ISSUE THREAD

**Issue by mfrobben** [rickeyski/node-beautifier#6]
TypeError: Property 'beauty' of object #<Object> is not a function
    at /Users/mrobben/devproj/sold-backend/node_modules/beautifier/bin/beautifier.js:3:478
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

**Comment by nullifiedaccount3** [comment]
+1

**Comment by luileito** [comment]
The `style_html` function is not exported, so just add this line at the end of `/usr/lib/node_modules/beautifier/lib/beautifier.js`: 

``` js
"undefined" !== typeof exports && (exports.html_beautify = style_html);
```

Cheers, 
Luis
